### PR TITLE
Add sed rule for export keyword

### PR DESCRIPTION
**Pull request by achorein**

### CODE REVIEW

**Comment by Anvil** [comment]
I think your patch is too complicated, but I get your point.

**Comment by achorein** [comment]
yes surely too complicated.
sed it's not my best friend but still usefull ^^

**Comment by Anvil** [comment]
Is https://github.com/Anvil/bash-doxygen/commit/cc13845afb847d087199b3c4cc7495403aff0310 okay with you ?

**Comment by achorein** [comment]
Yes

**Comment by Anvil** [comment]
Ack ! Thank you. Good day !

**Pull request closed without merging**
