### PR TITLE
Correctly handle indented comments

### PR DESCRIPTION
**Pull request by darnir**

### CODE REVIEW

**Comment by Anvil** [comment]
Thank you.

**Comment by joolswills** [comment]
I'm getting `doxygen-bash.sed line 157: Invalid back reference` since this PR.

sed (GNU sed) 4.5

**Comment by Anvil** [comment]
@joolswills does latest commit on master fix the issue ?

**Comment by joolswills** [comment]
Sorry for late reply. Seems to be ok now. Thanks.

**Pull request merged**
